tmp:
  image: mhart/alpine-node:0.12.7
  entrypoint: ['/bin/bash']
  volumes:
    - /ember-app/.sass-cache
    - /ember-app/node_modules
    - /ember-app/bower_components
    - /ember-app/tmp
default: &defaults
  build: .
  volumes:
    - .:/ember-app
  volumes_from:
    - tmp
ember:
  <<: *defaults
bash:
  <<: *defaults
  entrypoint: ['/bin/bash']
npm:
  <<: *defaults
  entrypoint: ['/usr/bin/npm', '--unsafe-perm']
bower:
  <<: *defaults
  entrypoint: ['/usr/bin/bower', '--allow-root']
server:
  <<: *defaults
  command: server --watcher polling
  ports:
    - "4200:4200"
    - "35729:35729" # legacy ember live reload port
    - "49152:49152" # ember 1.13.8 live reload port
